version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  build:
    commands:
      - echo Build started on `date`
      - ls #for execution test on docker environment
      - for file in `find src -type f -name "*.md"`;
            do
                out=`echo $file | sed -e s/\.md//`
                echo $out.pdf
            done
      - pandoc src/README-Template.md -f markdown -o src/README-Template.pdf -V documentclass=ltjarticle -V classoption=a4j -V geometry:margin=1in --pdf-engine=lualatex
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - src/README-Template.pdf
