version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  build:
    commands:
      - echo Build started on `date`
      - ls #for execution test on docker environment
      - mkdir -p _build
      - for file in `find src -type f -name "*.md"`;
          do
            out=`echo $file | sed -e s/src/_build/` | sed -e s/\.md//;
            echo $out.pdf;
            pandoc $file -f markdown -o $out.pdf -V documentclass=ltjarticle -V classoption=a4j -V geometry:margin=1in --pdf-engine=lualatex;
          done
      - ls _build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '_build/*'
